#[path = "../helpers/mod.rs"]
#[macro_use]
mod helpers;
use helpers::GameboyTestExt;

use gameman::gameboy::Gameboy;

test_rom!(
    div_write,
    "tests/mooneye/roms/timer/div_write.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim00,
    "tests/mooneye/roms/timer/tim00.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim01,
    "tests/mooneye/roms/timer/tim01.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim10,
    "tests/mooneye/roms/timer/tim10.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim11,
    "tests/mooneye/roms/timer/tim11.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim00_div_trigger,
    "tests/mooneye/roms/timer/tim00_div_trigger.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim01_div_trigger,
    "tests/mooneye/roms/timer/tim01_div_trigger.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim10_div_trigger,
    "tests/mooneye/roms/timer/tim10_div_trigger.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tim11_div_trigger,
    "tests/mooneye/roms/timer/tim11_div_trigger.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tima_reload,
    "tests/mooneye/roms/timer/tima_reload.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tma_write_reloading,
    "tests/mooneye/roms/timer/tma_write_reloading.gb",
    passes_mooneye_test_rom
);
test_rom!(
    tima_write_reloading,
    "tests/mooneye/roms/timer/tima_write_reloading.gb",
    passes_mooneye_test_rom
);
test_rom!(
    rapid_toggle,
    "tests/mooneye/roms/timer/rapid_toggle.gb",
    passes_mooneye_test_rom
);
