[package]
name = "gameman"
version = "0.1.0"
authors = ["Bart Merenda <outsbart@gmail.com>"]
edition = "2024"

[[test]]
name = "test_mooneye_instr_timing_roms"
path = "tests/mooneye/test_mooneye_instr_timing_roms.rs"

[[test]]
name = "test_mooneye_timer_roms"
path = "tests/mooneye/test_mooneye_timer_roms.rs"

[[test]]
name = "test_boot_roms"
path = "tests/mooneye/test_boot_roms.rs"

[[test]]
name = "test_mooneye_bits_roms"
path = "tests/mooneye/test_mooneye_bits_roms.rs"

[[test]]
name = "test_mooneye_instr_roms"
path = "tests/mooneye/test_mooneye_instr_roms.rs"

[[test]]
name = "test_mooneye_interrupts_roms"
path = "tests/mooneye/test_mooneye_interrupts_roms.rs"

[[test]]
name = "test_mooneye_oam_dma_roms"
path = "tests/mooneye/test_mooneye_oam_dma_roms.rs"

[[test]]
name = "test_mooneye_ppu_roms"
path = "tests/mooneye/test_mooneye_ppu_roms.rs"

[[test]]
name = "test_mooneye_serial_roms"
path = "tests/mooneye/test_mooneye_serial_roms.rs"

[[test]]
name = "test_halt_bug_rom"
path = "tests/blargg/test_halt_bug_rom.rs"

[[test]]
name = "test_interrupt_time_rom"
path = "tests/blargg/test_interrupt_time_rom.rs"

[[test]]
name = "test_oam_bug_roms"
path = "tests/blargg/test_oam_bug_roms.rs"

[[test]]
name = "test_cpu_instr_roms"
path = "tests/blargg/test_cpu_instr_roms.rs"

[[test]]
name = "test_instr_timing_rom"
path = "tests/blargg/test_instr_timing_rom.rs"

[[test]]
name = "test_sound_roms"
path = "tests/blargg/test_sound_roms.rs"

[[test]]
name = "test_mem_timing_roms"
path = "tests/blargg/test_mem_timing_roms.rs"

[[test]]
name = "test_mooneye_mbc1_roms"
path = "tests/mooneye/test_mooneye_mbc1_roms.rs"

[[test]]
name = "test_mooneye_mbc2_roms"
path = "tests/mooneye/test_mooneye_mbc2_roms.rs"

[[test]]
name = "test_mooneye_mbc5_roms"
path = "tests/mooneye/test_mooneye_mbc5_roms.rs"

[features]
default = ["sdl"]
sdl = ["dep:sdl2"]

[[bin]]
name = "gameman"
path = "src/bin/gameman.rs"
required-features = ["sdl"]

[dependencies]
log = "0.4.6"
sdl2 = { version = "0.38.0", optional = true }
serde_derive = "1.0.91"
csv = "1.0.7"
lazy_static = "1.3.0"
